# Generated by Django 4.2.19 on 2025-02-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_encryptedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncryptedFile',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
