# Generated by Django 4.2.19 on 2025-05-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_registrationkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationkey',
            name='created_at',
        ),
    ]
