# Generated by Django 4.2.19 on 2025-05-18 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='encrypted_files/')),
                ('filename', models.CharField(max_length=255)),
                ('encrypted_aes_key', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('rsa_public_key', models.BinaryField(blank=True, null=True)),
                ('rsa_private_key', models.BinaryField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
