# Generated by Django 4.2.19 on 2025-05-18 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encryptedfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Зашифрованный файл', 'verbose_name_plural': 'Зашифрованные файлы'},
        ),
        migrations.RemoveField(
            model_name='encryptedfile',
            name='rsa_private_key',
        ),
        migrations.RemoveField(
            model_name='encryptedfile',
            name='rsa_public_key',
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsa_public_key', models.BinaryField(blank=True, null=True)),
                ('rsa_private_key', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
