# Generated by Django 4.2.19 on 2025-05-18 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_alter_encryptedfile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userkeys',
            options={'verbose_name': 'Ключи пользователя', 'verbose_name_plural': 'Ключи пользователей'},
        ),
        migrations.RemoveField(
            model_name='userkeys',
            name='rsa_private_key',
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
